--- DDL ----


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE DEPARTMENT
(   DEPARTMENT_ID NUMBER(2) CONSTRAINT DEPARTMENT_PK PRIMARY KEY,
    DEPTNAME varchar2(20),
     CONSTRAINT UC_DEPARTMENT UNIQUE (DEPTNAME)
);

/*DONE----------------------------------------------------------------------------*/
CREATE TABLE DOCTOR
(   DOCTOR_ID NUMBER(4) CONSTRAINT DOCTOR_ID_PK PRIMARY KEY,
    HOSPITAL_ID NUMBER(5) /* FOREIGN KEY */,
    ADDRESS_ID NUMBER(5) /* FOREIGN KEY */,
    DEPARTMENT_ID NUMBER(2) /* FOREIGN KEY */,
    DFIRST_NAME VARCHAR2(10),
    DLAST_NAME VARCHAR2(10),
    DESIGNATION VARCHAR2(15)
);     
ALTER TABLE DOCTOR
    ADD CONSTRAINT DOCTOR_ADDRESS_ADDRESS_ID_FK FOREIGN KEY(ADDRESS_ID)
		REFERENCES ADDRESS(ADDRESS_ID);      

ALTER TABLE DOCTOR
ADD CONSTRAINT DOC_DEPT_DEPT_ID_FK FOREIGN KEY(DEPARTMENT_ID)
REFERENCES DEPARTMENT(DEPARTMENT_ID);


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE APPOINTMENT
(   APPOINTMENT_ID NUMBER(2),
    PATIENT_ID NUMBER(5) /*FOREIGN KEY*/,
    DOCTOR_ID NUMBER(4) /* FOREIGN KEY*/,
    DEPARTMENT_ID NUMBER(2) /* FOREIGN KEY*/,
    DATE_TIME TIMESTAMP,
    REASON VARCHAR2(30),
    STATUS CHAR(1),
    CONSTRAINT UC_APPOINTMENT UNIQUE (APPOINTMENT_ID)
);

ALTER TABLE APPOINTMENT
    ADD CONSTRAINT APPT_PATIENT_PATIENT_ID_FK FOREIGN KEY(PATIENT_ID)
		REFERENCES PATIENT(PATIENT_ID);       
ALTER TABLE APPOINTMENT
    ADD CONSTRAINT APPT_DOCT_DOCTOR_ID_FK FOREIGN KEY(DOCTOR_ID)
		REFERENCES DOCTOR(DOCTOR_ID); 

ALTER TABLE APPOINTMENT
    ADD CONSTRAINT APPT_DEPT_DEPT_ID_FK FOREIGN KEY(DEPARTMENT_ID)
		REFERENCES DEPARTMENT(DEPARTMENT_ID);   



/*DONE----------------------------------------------------------------------------*/
CREATE TABLE MEDICINE
(   MEDICINE_ID NUMBER(10) CONSTRAINT MEDICINE_ID_PK PRIMARY KEY,
    MEDNAME VARCHAR2(15),
    QUANTITY NUMBER(3),
    PRICE NUMBER(8,2)
);


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE PRESCRIPTION
(   PRESCRIPTION_ID NUMBER(15) CONSTRAINT PRESCRIPTION_PK PRIMARY KEY, 
    MEDICINE_ID NUMBER(10)/* FOREIGN KEY*/,
    QUANTITY NUMBER(3)
);

ALTER TABLE PRESCRIPTION
    ADD CONSTRAINT PRESC_MED_MED_ID_FK FOREIGN KEY(MEDICINE_ID)
		REFERENCES MEDICINE(MEDICINE_ID);   

/*DONE----------------------------------------------------------------------------*/
CREATE TABLE DIAGNOSIS
(   DIAGNOSIS_ID NUMBER(15) CONSTRAINT DIAGNOSIS_PK PRIMARY KEY,
    APPOINTMENT_ID NUMBER(2), /* FOREIGN KEY */
    DATE_TIME TIMESTAMP,
    DISEASE VARCHAR2(20)
);


ALTER TABLE DIAGNOSIS
    ADD CONSTRAINT DIAGNOSIS_APPT_APPT_ID_FK FOREIGN KEY(APPOINTMENT_ID)
		REFERENCES APPOINTMENT(APPOINTMENT_ID);       

/*DONE----------------------------------------------------------------------------*/
CREATE TABLE RXDIAGNOSIS_MAPPING
(
	PRESCRIPTION_ID NUMBER(15),
	DIAGNOSIS_ID NUMBER(15),
    CONSTRAINT PK_RXDIAGNOSIS_MAPPING PRIMARY KEY (PRESCRIPTION_ID,DIAGNOSIS_ID)
);


/* DONE----------------------------------------------------------------------------*/
CREATE TABLE MEDRESULT
(   MEDRESULT_ID NUMBER(15) CONSTRAINT MEDICAL_RESULT_PK PRIMARY KEY,
    EXAMINATION_ID NUMBER(15), /* FOREIGN KEY */
    RESULT VARCHAR2(30),
    DATE_TIME TIMESTAMP
);

ALTER TABLE MEDRESULT
    ADD CONSTRAINT MEDRESULT_EXAM_EXAM_ID_FK FOREIGN KEY(EXAMINATION_ID)
		REFERENCES EXAMINATION(EXAMINATION_ID);       

/*DONE----------------------------------------------------------------------------*/
CREATE TABLE MEDRESULT_DIAGNOSIS_MAPPING
(
    MEDRESULT_ID NUMBER(15),
    DIAGNOSIS_ID NUMBER(15),
    CONSTRAINT PK_MEDRESULT_DIAGNOSIS_MAPPING PRIMARY KEY (MEDRESULT_ID,DIAGNOSIS_ID)
);


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE EXAMINATION
(   EXAMINATION_ID NUMBER(15) CONSTRAINT EXAMINATION_ID PRIMARY KEY,
    EXAMNAME VARCHAR2(10),
    EXAMDETAILS VARCHAR2(30),
    DATE_TIME TIMESTAMP
);

/*DONE----------------------------------------------------------------------------*/
CREATE TABLE ADDRESS
(   ADDRESS_ID NUMBER(5) CONSTRAINT ADDRESS_ID_PK PRIMARY KEY,
    ADDRESS_TYPE VARCHAR2(10),
    FULL_ADDRESS VARCHAR2(50),
    ZIP NUMBER(5)
);


/* DONE----------------------------------------------------------------------------*/
CREATE TABLE PATIENT
(   PATIENT_ID NUMBER(5) CONSTRAINT PATIENT_ID_PK PRIMARY KEY,
    ADDRESS_ID NUMBER(5),
    PFIRST_NAME VARCHAR2(15),
    PLAST_NAME VARCHAR2(15),
    DOB DATE,
    EMAIL_ADDRESS VARCHAR2(40),
    PHONE_NUMBER VARCHAR2(10),
    GENDER CHAR(1),
    MARITAL_STATUS CHAR(2),
    INSURANCE_ID NUMBER(9),
    SSN NUMBER(9)
);

#DONE
ALTER TABLE PATIENT
    ADD CONSTRAINT PATIENT_ADDRESS_ADDRESS_ID_FK FOREIGN KEY(ADDRESS_ID)
		REFERENCES ADDRESS(ADDRESS_ID);



/*DONE----------------------------------------------------------------------------*/
CREATE TABLE HEALTH_BEHAVIOR_TRACKING
(   HEALTH_BEHAVIOR_TRACKING_ID NUMBER(10) CONSTRAINT HEALTH_BEHAVIOR_TRACKING_ID PRIMARY KEY,
    PATIENT_ID NUMBER(5),
    EXERCISE VARCHAR2(30),
    MEAL VARCHAR2(15),
    GLUCOSE_LEVEL NUMBER(2,2),
    BLOOD_PRESSURE NUMBER(3),
    WEIGHT NUMBER(3),
    DATE_TIME TIMESTAMP   
);

ALTER TABLE HEALTH_BEHAVIOR_TRACKING
    ADD CONSTRAINT H_B_T_PATIENT_PATIENT_ID_FK FOREIGN KEY(PATIENT_ID)
    REFERENCES PATIENT(PATIENT_ID);


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE POST
(   POST_ID NUMBER(10) CONSTRAINT POST_ID_PK PRIMARY KEY,
    POST_CATEGORY_ID NUMBER(10),
    PATIENT_ID NUMBER(5),
    HEALTH_BEHAVIOR_TRACKING_ID NUMBER(10),
    CONTENT VARCHAR2(30),
    IMAGE BLOB,
    DATE_TIME TIMESTAMP
);

ALTER TABLE POST
    ADD CONSTRAINT POST_PST_CTGRY_PST_CTGRY_ID_FK FOREIGN KEY(POST_CATEGORY_ID)
		REFERENCES POST_CATEGORY(POST_CATEGORY_ID);

#DONE
ALTER TABLE POST
    ADD CONSTRAINT POST_PATIENT_PATIENT_ID_FK FOREIGN KEY(PATIENT_ID)
		REFERENCES PATIENT(PATIENT_ID);


ALTER TABLE POST
    ADD CONSTRAINT POST_H_B_T_H_B_T_ID_FK FOREIGN KEY(HEALTH_BEHAVIOR_TRACKING_ID)
		REFERENCES HEALTH_BEHAVIOR_TRACKING(HEALTH_BEHAVIOR_TRACKING_ID);


/*DONE----------------------------------------------------------------------------*/
CREATE TABLE POST_CATEGORY
(   POST_CATEGORY_ID NUMBER(10) CONSTRAINT POST_CATEGORY_ID_PK PRIMARY KEY,
    POSTNAME VARCHAR2(15)
);


/*DONE---------------------------------------------ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENTS_POST_POST_ID_FK FOREIGN KEY(POST_ID)
		REFERENCES POST(POST_ID);-------------------------------*/
CREATE TABLE COMMENTS
( COMMENTS_ID NUMBER(10) CONSTRAINT COMMENTS_PK PRIMARY KEY,
    POST_ID NUMBER(10),
    EMAIL VARCHAR2(30),
    CONTENT VARCHAR2(30),
    DATE_TIME TIMESTAMP
);
#DONE
ALTER TABLE COMMENTS
    ADD CONSTRAINT COMMENTS_POST_POST_ID_FK FOREIGN KEY(POST_ID)
		REFERENCES POST(POST_ID);



